'use strict';
const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
(async()=>{
const server=require('http').createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(process.env.WERKBANK_PAGE||'werkbank-design-preview.html'));});await new Promise(r=>server.listen(8879,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.WERKBANK_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-gpu']});const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(6000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
await page.goto('http://127.0.0.1:8879');await page.click('#design-new');await page.click('#add-material');await page.locator('.profile-card').filter({has:page.locator('input[value="rectTube"]')}).click();await page.locator('#catalog-choices label').filter({hasText:'50 × 30 × 2 mm'}).first().click();await page.fill('#e-length','1000');await page.fill('#e-count','4');await page.click('#editor-save');await page.click('#cost-save');
// A later catalog price must never replace a saved line on edit.
await page.evaluate(()=>{catalogArticle(costState.materials[0].catalogArticleId).price.amount=9.99;});await page.click('[data-edit]');assert.equal(await page.inputValue('#e-unitPrice'),'4.29');await page.fill('#e-count','5');await page.click('#editor-save');assert.match(await page.locator('.line-price strong').innerText(),/21,45/);
await page.click('[data-edit]');await page.fill('#e-unitPrice','7');await page.click('#reset-catalog-price');assert.equal(await page.inputValue('#e-unitPrice'),'');await page.click('#editor-save');assert.match(await page.locator('.line-price strong').innerText(),/49,95/);
await page.click('[data-edit]');await page.selectOption('#e-priceBasis','kg');assert.equal(await page.inputValue('#e-unitPrice'),'');assert(await page.locator('#editor-save').isDisabled());await page.fill('#e-unitPrice','3');await page.click('#editor-cancel');await page.waitForSelector('.editor-backdrop',{state:'detached'});assert.match(await page.locator('.line-price strong').innerText(),/49,95/);
// Material change removes an incompatible article and never duplicates a field.
await page.click('[data-edit]');const materials=await page.locator('#e-material option').evaluateAll(nodes=>nodes.map(x=>x.value));if(materials.length>1){await page.selectOption('#e-material',materials.find(x=>x!=='s235'));assert.equal(await page.locator('#e-material').count(),1);assert.equal(await page.evaluate(()=>activeMaterialEditor.state.draft.catalogArticleId),undefined);}await page.click('#editor-cancel');
// Every actual generated profile route opens, has unique IDs, traps focus and cancels.
const profiles=await page.evaluate(()=>MATERIAL_PROFILE_TYPES);for(const type of profiles){await page.click('#add-material');await page.locator('.profile-card').filter({has:page.locator('input[value="'+type+'"]')}).click();assert(await page.locator('#editor-save').isVisible());const ids=await page.locator('[id]').evaluateAll(nodes=>nodes.map(x=>x.id));assert.equal(ids.length,new Set(ids).size,type);await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('.material-editor')));await page.keyboard.press('Escape');await page.waitForSelector('.editor-backdrop',{state:'detached'});}
assert.equal(await page.evaluate(()=>document.querySelector('.wrap').inert),false);
// Every researched catalog article validates with a requested length, including UNP/UPE/T.
const catalogErrors=await page.evaluate(()=>CATALOG_ARTICLES.map(a=>{const line=applyCatalogArticle({...newLine(),profile:a.profileType},a);line.dims.length=line.dims.length||1000;const errors=validateLine(line,1);return Object.keys(errors).length?{id:a.id,errors}:null;}).filter(Boolean));assert.deepEqual(catalogErrors,[]);
for(const profile of ['UNP','UPE','tee']){await page.click('#add-material');await page.locator('.profile-card').filter({has:page.locator('input[value="'+profile+'"]')}).click();const material=profile==='UPE'?'s355':profile==='tee'?'alu':'s235';await page.selectOption('#e-material',material);await page.locator('#catalog-choices input:not([value="custom"])').first().locator('..').click();await page.fill('#e-length','1000');assert.equal(await page.locator('#editor-save').isDisabled(),false,profile);await page.click('#editor-cancel');}
// Quota failure retains the previous saved data and gives a usable error.
await page.click('#cost-save');const before=await page.evaluate(()=>localStorage.getItem(STORE.calculations));await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});await page.click('#cost-save');assert.match(await page.locator('#cost-content').innerText(),/Backup mislukt/);assert.equal(await page.evaluate(()=>localStorage.getItem(STORE.calculations)),before);
const blocked=await browser.newPage();blocked.on('pageerror',e=>errors.push(e.message));await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError');}}));await blocked.goto('http://127.0.0.1:8879');assert(await blocked.locator('.storage-status').isVisible());await blocked.click('#design-new');assert(await blocked.locator('#cost').isVisible());assert.deepEqual(errors,[]);await browser.close();server.close();console.log('Browser edge cases: snapshot, reset, price basis, 18 profiles, focus/cancel, quota and blocked storage passed.');
})().catch(e=>{console.error(e);process.exit(1);});
