/* Workshop 02: interaction and accessibility refinements, preview only. */
let savedProjectId=null;
let cleanProject='';
const serial=()=>JSON.stringify(costState||{},(_key,value)=>typeof value==='number'?String(value):value);
function currentDirty(){return !!costState&&serial()!==cleanProject;}
function allowDiscard(){return !currentDirty()||confirm('Je calculatie heeft onbewaarde wijzigingen. Toch een ander project openen?');}
function displayDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?'Datum onbekend':date.toLocaleDateString('nl-NL',{day:'numeric',month:'short'});}
function savedProjects(){const list=safeGet(STORE.calculations,[]);return Array.isArray(list)?list.filter(x=>x&&typeof x.id==='string'&&x.data&&typeof x.data==='object'):[];}
function openSavedProject(row){if(!row||!allowDiscard())return;designTab='materials';savedProjectId=row.id;history.pushState(null,'','#kostprijs');hidePages();$('cost').hidden=false;renderCostPage(migrateCalculation(row.data));cleanProject=serial();setNav('home');window.scrollTo({top:0});}
function startProject(){if(!allowDiscard())return;savedProjectId=null;designTab='materials';history.pushState(null,'','#kostprijs');hidePages();$('cost').hidden=false;renderCostPage();cleanProject=serial();setNav('home');window.scrollTo({top:0});}
renderDashboard=function(){const rows=savedProjects();$('recent-design').innerHTML=rows.length?rows.slice(0,5).map(x=>'<button class="recent-row" data-recent="'+esc(x.id)+'">'+uiIcon('document')+'<span><b>'+esc(x.data.project||'Naamloze calculatie')+'</b><small>'+esc(displayDate(x.datum))+' · '+(x.data.materials?.length||0)+' materiaalregels</small></span><span aria-hidden="true" style="flex:0">›</span></button>').join(''):'<div class="recent-empty"><b>Ruimte voor je volgende project.</b><p>Begin met een profiel, een maat en een hoeveelheid. Je bewaarde calculaties verschijnen hier.</p></div>';$('recent-design').querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>openSavedProject(rows.find(x=>x.id===b.dataset.recent)));$('quick-design').innerHTML=homeTools.map(([id,name,desc,icon])=>'<a class="quick-tool" href="#'+id+'">'+uiIcon(icon,'tool-art')+'<b>'+name+'</b><small>'+desc+'</small></a>').join('');};
// Exactly one material selector and one description field per editor.
const unpolishedDimensions=dimensionsHtml;
dimensionsHtml=function(d){const template=document.createElement('template');template.innerHTML=unpolishedDimensions(d);template.content.querySelector('#e-material')?.parentElement.remove();template.content.querySelector('#e-description')?.parentElement.parentElement.remove();return template.innerHTML;};
// Price snapshots are retained while opening/editing a saved material line.
const unpolishedPricing=pricingHtml;
pricingHtml=function(d){const t=document.createElement('template');t.innerHTML=unpolishedPricing(d);const price=t.content.querySelector('#e-unitPrice');if(d.priceMode==='manual')price.value=d.unitPrice??'';price.setAttribute('value',price.value);const label=t.content.querySelector('label[for="e-unitPrice"]');if(label)label.textContent='Prijs voor deze regel';const hint=document.createElement('p');hint.className='hint';hint.textContent=d.priceMode==='manual'?'Deze vastgelegde prijs blijft behouden. Je kunt hem zelf wijzigen.':'Laat leeg om de catalogusrichtprijs te gebruiken.';price.parentElement.after(hint);return t.innerHTML;};
collectDraft=function(d,root){if(root.dataset.redrawing==='true')return;const lockedArticle=catalogArticle(d.catalogArticleId);const dimensionKeys=new Set(PROFILES[d.profile]?.dims||[]);root.querySelectorAll('input[id^="e-"],select[id^="e-"],textarea[id^="e-"]').forEach(el=>{const k=el.id.slice(2);if(k==='unitPrice')return;if(dimensionKeys.has(k)){d.dims=d.dims||{};if(!lockedArticle||k==='length')d.dims[k]=el.value;}else d[k]=el.type==='checkbox'?el.checked:el.value;});if(lockedArticle){for(const [key,value] of Object.entries(lockedArticle.dimensionsMm))if(key!=='length')d.dims[key]=value;}const own=root.querySelector('#e-unitPrice');if(own&&own.value.trim()!==''){const changed=strictNumber(own.value)!==strictNumber(d.unitPrice);d.unitPrice=own.value;d.priceMode='manual';if(changed)d.priceOrigin='user';}else if(own&&d.priceMode==='manual'&&own.dataset.edited==='true'){d.unitPrice='';d.priceOrigin='user';}else if(catalogArticle(d.catalogArticleId)&&d.priceMode!=='manual'){d.priceMode='catalog';d.priceOrigin='catalog';d.unitPrice=catalogArticle(d.catalogArticleId).price.amount??'';}};
const unpolishedBind=bindMaterialEditor;
bindMaterialEditor=function(state,root,touched,draw){const originalDraw=draw;draw=()=>{root.dataset.redrawing='true';try{originalDraw();}finally{delete root.dataset.redrawing;}};unpolishedBind(state,root,touched,draw);const field=root.querySelector('#e-material');if(field)field.addEventListener('change',()=>{collectDraft(state.draft,root);const chosen=field.value;if(catalogArticle(state.draft.catalogArticleId)?.material!==chosen){delete state.draft.catalogArticleId;delete state.draft.catalogSize;delete state.draft.priceSnapshot;state.draft.supplierKgm='';state.draft.unitPrice='';state.draft.priceOrigin='catalog';state.draft.priceMode='catalog';}draw();});const own=root.querySelector('#e-unitPrice');if(own)own.addEventListener('input',()=>{own.dataset.edited='true';state.draft.priceOrigin='user';state.draft.priceMode='manual';state.draft.unitPrice=own.value;updateMaterialPreview(state.draft,root);});const basis=root.querySelector('#e-priceBasis');if(basis)basis.addEventListener('change',()=>{state.draft.priceMode='manual';state.draft.priceOrigin='user';state.draft.unitPrice='';const price=root.querySelector('#e-unitPrice');if(price){price.value='';price.dataset.edited='true';}updateMaterialPreview(state.draft,root);});const change=root.querySelector('#change-profile');if(change)change.addEventListener('click',()=>{if(state.materialEditorView==='picker'){for(const k of ['catalogArticleId','catalogSize','supplierKgm','priceSnapshot','previousPriceSnapshot','partWidth','partLength'])delete state.draft[k];state.draft.unitPrice='';state.draft.priceMode='catalog';state.draft.priceOrigin='catalog';}});const title=root.querySelector('#editor-title');if(title)title.textContent=state.materialEditorView==='picker'?'Kies een profiel':state.editing?'Materiaal bewerken':'Materiaal toevoegen';const search=root.querySelector('#profile-search');if(search){const message=document.createElement('p');message.className='search-empty';message.hidden=true;message.setAttribute('role','status');message.textContent='Geen profiel gevonden. Probeer bijvoorbeeld koker of buis.';root.querySelector('#profile-picker').after(message);search.addEventListener('input',()=>{message.hidden=Array.from(root.querySelectorAll('.profile-card')).some(c=>!c.hidden);});}root.querySelectorAll('input[name="catalog-article"]').forEach(el=>{el.closest('label').classList.toggle('is-selected',el.checked);});};
// Include every validation error in the summary, including hidden article metadata.
visibleEditorErrors=function(d){return validateLine(d,positiveInt(costState.qty)||1);};
const unpolishedPreview=updateMaterialPreview;
updateMaterialPreview=function(d,root){unpolishedPreview(d,root);const errors=visibleEditorErrors(d,root);const hidden=Object.entries(errors).filter(([key])=>!root.querySelector('#e-'+key));root.querySelector('#editor-error-summary').textContent=hidden.map(([,message])=>message).join(' ');};
// Dialog focus stays inside visible, enabled controls. Background is inert.
const unpolishedOpenEditor=openMaterialEditor;
openMaterialEditor=function(source){const editor=unpolishedOpenEditor(source),overlay=editor.overlay;editor.state.editing=!!source;const wrap=document.querySelector('.wrap'),oldInert=wrap.inert;wrap.inert=true;const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';function available(el){if(el.disabled||el.closest('[hidden]'))return false;for(let p=el.parentElement;p&&p!==overlay;p=p.parentElement){if(p.tagName==='DETAILS'&&!p.open&&!p.querySelector('summary')?.contains(el))return false;}return el.tabIndex>=0;}
overlay.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();$('editor-cancel').click();return;}if(e.key==='Tab'){const nodes=Array.from(overlay.querySelectorAll('button,input,select,textarea,a[href],summary,[tabindex]')).filter(available),first=nodes[0],last=nodes.at(-1);if(!nodes.length)return;if(e.shiftKey&&(e.target===first||!nodes.includes(e.target))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(e.target===last||!nodes.includes(e.target))){e.preventDefault();first.focus();}}};const observer=new MutationObserver(()=>{if(!overlay.isConnected){wrap.inert=oldInert;document.body.style.overflow=oldOverflow;observer.disconnect();if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}});observer.observe(document.body,{childList:true});return editor;};
function materialTitle(l){const a=catalogArticle(l.catalogArticleId);if(l.profile==='purchasedItem')return l.description||'Inkoopartikel';if(a)return (PROFILES[l.profile]?.name||'Profiel')+' '+a.label;if(l.catalogSize)return (PROFILES[l.profile]?.name||'Profiel')+' '+l.catalogSize;const d=l.dims||{},vals=PROFILES[l.profile]?.fields.filter(x=>x.key!=='length').map(x=>d[x.key]).filter(x=>x!==undefined&&x!=='')||[];return (PROFILES[l.profile]?.name||'Materiaal')+(vals.length?' '+vals.join(' × '):'');}
const unpolishedMaterialCard=materialCard;
materialCard=function(x){const l=x.line,r=x.result;if(r.errors)return unpolishedMaterialCard(x);const basis={kg:'kg',m:'m',m2:'m²',piece:'stuk',wholeBar:'stang',wholePlate:'plaat'},origin=l.priceOrigin==='user'?'Eigen inkoopprijs':l.priceSnapshot?'Vastgelegde catalogusprijs':r.priceSource;return'<article class="material-card">'+profileIcon(l.profile)+'<div class="material-main"><div class="material-title">'+esc(materialTitle(l))+'</div><div class="material-meta">'+esc(MATERIALS[l.material]?.name||'')+' · '+r.N+' × '+(l.dims?.length?fmt(strictNumber(l.dims.length),0)+' mm':'stuk')+'</div><div class="line-price"><span>'+(r.price===null?'Op aanvraag':euro(r.price)+' / '+esc(basis[l.priceBasis]||l.priceBasis))+'</span><strong>'+(r.lineCents===null?'Prijs ontbreekt':euro(r.lineCents/100))+'</strong></div><small class="material-meta">'+esc(origin)+'</small><details class="line-details"><summary>Gewicht en prijsdetails</summary><p>'+fmt(r.weight,3)+' kg · '+esc(r.weightBasis)+'</p><p>Factureerbaar: '+fmt(r.billable,3)+' '+esc(basis[l.priceBasis]||l.priceBasis)+(r.waste?' · '+fmt(r.waste,1)+'% reserve':'')+'</p>'+(l.note?'<p>'+esc(l.note)+'</p>':'')+'</details></div><div class="row-actions no-print"><button data-edit="'+esc(l.id)+'" aria-label="Bewerk '+esc(materialTitle(l))+'">'+uiIcon('edit')+'</button><button data-copy="'+esc(l.id)+'" aria-label="Dupliceer '+esc(materialTitle(l))+'">'+uiIcon('copy')+'</button><button data-remove="'+esc(l.id)+'" aria-label="Verwijder '+esc(materialTitle(l))+'">'+uiIcon('trash')+'</button></div></article>';};
Object.assign(UI_PATHS,{edit:'M4 16L16 4l4 4L8 20H4z M14 6l4 4',copy:'M8 8h12v12H8z M4 16V4h12',trash:'M4 6h16 M9 3h6 M6 6l1 15h10l1-15 M10 10v7 M14 10v7'});
const unpolishedMaterials=renderMaterials;
renderMaterials=function(){unpolishedMaterials();const root=$('material-content');const meta=document.createElement('details');meta.className='material-analysis';meta.innerHTML='<summary>Verbruik, inkoop en uitsplitsing</summary>';Array.from(root.children).filter(el=>!el.classList.contains('material-list')).forEach(el=>meta.append(el));root.append(meta);};
function updateStickyTotal(){const total=$('sticky-cost');if(!total)return;const labels=Array.from(document.querySelectorAll('#cost-result .cost-breakdown span'));const label=labels.find(x=>x.textContent==='Kostprijs na opslag');const incomplete=$('cost-result')?.querySelector('.incomplete,.err');total.textContent=incomplete?'Controleer overzicht':label?.nextElementSibling?.textContent||'—';}
const unpolishedTotals=renderCostTotals;
renderCostTotals=function(){unpolishedTotals();updateStickyTotal();};
const unpolishedCost=renderCostPage;
renderCostPage=function(values,message){unpolishedCost(values,message);const content=$('cost-content'),tabs=content.querySelector('.cost-tabs'),blocks=Array.from(content.querySelectorAll(':scope > .cost-block'));const costResult=$('cost-result');for(const [id,name] of [['materials','Materiaal'],['labor','Arbeid'],['overview','Overzicht']]){const panel=document.createElement('div');panel.id='panel-'+id;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby','tab-'+id);panel.tabIndex=0;tabs.after(panel);blocks.filter(b=>b.dataset.designGroup===id).forEach(b=>{b.hidden=false;panel.append(b);});if(id==='overview')panel.append(costResult);const tab=$('tab-'+id);tab.setAttribute('aria-controls',panel.id);tab.onclick=()=>{designTab=id;tabs.querySelectorAll('button').forEach(b=>{const active=b.dataset.tab===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});content.querySelectorAll('[role="tabpanel"]').forEach(p=>p.hidden=p.id!=='panel-'+id);costResult.hidden=false;};} $('tab-'+designTab).click();const actions=$('cost-save').parentElement;actions.classList.remove('card');const extras=document.createElement('details');extras.className='project-extras';extras.innerHTML='<summary>Importeren, exporteren en printen</summary><div class="actions"></div>';Array.from(actions.children).filter(el=>el.id!=='cost-save').forEach(el=>extras.lastElementChild.append(el));actions.before(extras);actions.insertAdjacentHTML('afterbegin','<div class="sticky-summary"><small>Kostprijs excl. btw</small><strong id="sticky-cost">—</strong></div>');$('cost-save').textContent='Calculatie bewaren';$('cost-new').onclick=startProject;$('cost-save').onclick=saveCalculation;const details=content.querySelector('.cost-project')?.parentElement;if(details){const fields=document.createElement('details');fields.className='project-fields';fields.innerHTML='<summary>Projectgegevens</summary>';details.before(fields);fields.append(details);if(!costState.project)fields.open=true;}updateStickyTotal();};
saveCalculation=function(){const data=serializableState(),qty=positiveInt(data.qty),calc=calculateMaterialList(data.materials,qty,getPrices());if(!qty||calc.rows.some(x=>x.result.errors)||$('cost-result').querySelector('.err')){renderCostPage(data,'Bewaren afgebroken: controleer de invoer in het overzicht.');return;}data.materials.forEach(l=>{const r=calculateMaterialLine(l,qty,getPrices());if(r.price!==null){l.priceMode='manual';l.unitPrice=r.price;if(!l.priceSnapshot)l.priceSnapshot={price:r.price,basis:l.priceBasis,source:r.priceSource,date:new Date().toISOString()};}});const previous=storageAdapter.read(STORE.calculations,[]);if(!previous.ok||!Array.isArray(previous.value)){renderCostPage(data,'Bestaande opslag kon niet veilig worden gelezen. Exporteer je huidige calculatie; er is niets overschreven.');return;}if(previous.value.length&&!safeSet(STORE.calculations+'.backup',previous.value)){renderCostPage(data,'Backup mislukt. Exporteer je calculatie; er is niets overschreven.');return;}const id=savedProjectId||uid(),entry={id,datum:new Date().toISOString(),schemaVersion:MATERIAL_SCHEMA,data},list=[entry,...previous.value.filter(x=>x.id!==id)];if(!safeSet(STORE.calculations,list)){renderCostPage(data,'Opslag is vol of geblokkeerd. Exporteer je calculatie; bewaren is niet gelukt.');return;}savedProjectId=id;renderCostPage(data,'Calculatie bewaard.');cleanProject=serial();};
const unpolishedSaved=renderSavedCosts;
renderSavedCosts=function(){unpolishedSaved();$('saved-costs').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openSavedProject(savedProjects().find(x=>x.id===b.dataset.open)));};
const unpolishedImport=importCalculation;
importCalculation=async function(e){if(!allowDiscard()){e.target.value='';return;}await unpolishedImport(e);if($('cost-content').textContent.includes('Calculatie veilig geïmporteerd')){savedProjectId=null;cleanProject='';}};
const unpolishedRoute=routeHash;
routeHash=function(){if(location.hash==='#projecten'){hidePages();$('design-projects').hidden=false;renderProjectLibrary();setNav('home');return;}unpolishedRoute();if(location.hash==='#kostprijs')setNav('home');};
window.removeEventListener('hashchange',unpolishedRoute);window.addEventListener('hashchange',routeHash);window.addEventListener('popstate',routeHash);
const unpolishedHide=hidePages;
hidePages=function(){if(costState&&!$('cost').hidden)readCostInput();unpolishedHide();$('design-projects').hidden=true;};
function renderProjectLibrary(){const rows=savedProjects();$('all-projects').innerHTML=rows.length?rows.map(row=>'<button class="recent-row" data-project="'+esc(row.id)+'">'+uiIcon('document')+'<span><b>'+esc(row.data.project||'Naamloze calculatie')+'</b><small>'+esc(displayDate(row.datum))+'</small></span><span aria-hidden="true" style="flex:0">›</span></button>').join(''):'<p class="recent-empty">Nog geen calculaties bewaard.</p>';$('all-projects').querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openSavedProject(rows.find(x=>x.id===b.dataset.project)));}
$('design-new').onclick=startProject;$('library-new').onclick=startProject;
const unpolishedTheme=applyTheme;
applyTheme=function(value){unpolishedTheme(value);document.querySelectorAll('[data-design-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.designTheme===value)));};
window.addEventListener('beforeunload',e=>{if(currentDirty()){e.preventDefault();e.returnValue='';}});
routeHash();cleanProject=serial();applyTheme(safeGet(STORE.theme,'dark'));
/* Final visual pass: navigation, useful profile order, complete vector family. */
const polishedSetNav=setNav;
setNav=function(route){polishedSetNav(route);document.body.dataset.view=$('cost').hidden?'browse':'cost';};
const extraProfileIcon=profileIcon;
profileIcon=function(type,label=''){
 const shapes={squareBar:'M14 32h26v28H14z M14 32l37-19h26v28L40 60 M40 32l37-19',hexBar:'M20 31h18l9 14-9 15H20l-9-15z M20 31l35-18h18l9 14-9 15L38 60 M38 31l35-18 M47 45l35-18',UNP:'M12 30h29v6H18v21h23v6H12z M12 30l38-18h29v6L41 36 M41 57l38-18v6L41 63',UPE:'M12 30h29v5H17v23h24v5H12z M12 30l38-18h29v5L41 35 M41 58l38-18v5L41 63',tee:'M10 31h32v5H29v27h-6V36H10z M10 31l38-18h32v5L42 36 M29 63l38-18V24',customKgM:'M13 35l32-18 29 15-32 18z M13 35v22l29 16 32-20V32 M42 50v23',purchasedItem:'M15 29l28-13 29 13-29 14z M15 29v29l28 15 29-15V29 M43 43v30 M30 22l28 14v12'};
 if(!shapes[type])return extraProfileIcon(type,label);
 return '<svg class="profile-icon" viewBox="0 0 88 80" role="img" aria-label="'+esc(PROFILES[type]?.name||type)+'"><path d="'+shapes[type]+'" fill="currentColor" fill-opacity=".08" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/></svg>';
};
pickerHtml=function(){const order=['squareTube','rectTube','roundTube','equalAngle','IPE','HEA','HEB','plate','strip','roundBar','squareBar','hexBar','unequalAngle','UNP','UPE','tee','customKgM','purchasedItem'];return '<div class="profile-search-wrap"><label class="visually-hidden" for="profile-search">Zoek een profiel</label><input class="profile-search" id="profile-search" type="search" placeholder="Zoek een profiel" autocomplete="off"></div><div class="profile-picker" id="profile-picker">'+order.map(k=>'<label class="profile-card"><input type="radio" name="material-profile" value="'+k+'" class="profile-radio">'+profileIcon(k)+'<span>'+esc(PROFILES[k].name)+'</span></label>').join('')+'</div>';};
const shortTitle=materialTitle;
materialTitle=function(l){return shortTitle(l).replace('Rechthoekige koker','Koker').replace('Vierkante koker','Koker').replace('Gelijkzijdige hoeklijn','Hoeklijn');};
const textInput=editorInput;
editorInput=function(id,label,value,unit){return textInput(id,label,value,unit).replace('inputmode="decimal"','inputmode="'+(unit?'decimal':'text')+'"');};
const latestPreview=updateMaterialPreview;
updateMaterialPreview=function(d,root){latestPreview(d,root);const number=root.querySelector('.material-accordion>details:nth-child(5)>summary span');if(number)number.textContent=(d.count||'—')+(d.countMode==='perProduct'?' per eindproduct':' voor project');};
const latestCost=renderCostPage;
renderCostPage=function(values,message){latestCost(values,message);const fields=document.querySelector('.project-fields');if(fields)fields.open=!costState.project;$('add-material').addEventListener('click',()=>{if(fields&&costState.project)fields.open=false;});$('cost-title').parentElement.parentElement.classList.add('project-header');if(!$('project-back'))$('cost-title').parentElement.before(Object.assign(document.createElement('a'),{id:'project-back',href:'#home',className:'back-link',textContent:'←',ariaLabel:'Terug naar calculaties'}));$('saved-costs').hidden=true;};
const latestOpenEditor=openMaterialEditor;
openMaterialEditor=function(source){const result=latestOpenEditor(source);document.body.classList.add('dialog-open');const obs=new MutationObserver(()=>{if(!result.overlay.isConnected){document.body.classList.remove('dialog-open');obs.disconnect();}});obs.observe(document.body,{childList:true});return result;};
// Theme is available in settings; header select remains accessible and compact.
$('design-new').textContent='+ Nieuwe calculatie';
const toolsInputHandler=()=>{$('q').dispatchEvent(new Event('input',{bubbles:true}));};
const filteredMenu=renderMenu;
renderMenu=function(){filteredMenu();toolsInputHandler();};
routeHash();cleanProject=serial();
const finalCost=renderCostPage;
renderCostPage=function(values,message){finalCost(values,message);const options=$('c-costMethod')?.options;if(options){options[0].textContent='Netto verbruik uit voorraad';options[1].textContent='Hele aankoop voor dit project';}const save=$('cost-save');save.setAttribute('aria-label','Calculatie bewaren');};
// Print all three sections, then restore exactly the previous disclosure states.
let printDisclosures=[];
window.addEventListener('beforeprint',()=>{printDisclosures=Array.from(document.querySelectorAll('#cost details')).map(el=>[el,el.open]);printDisclosures.forEach(([el])=>el.open=true);});
window.addEventListener('afterprint',()=>{printDisclosures.forEach(([el,open])=>el.open=open);printDisclosures=[];});
if(!storageAdapter.read(STORE.calculations,[]).ok){const note=document.createElement('p');note.className='storage-status';note.setAttribute('role','status');note.textContent='Lokale opslag is niet beschikbaar. Je kunt rekenen en exporteren; bewaren lukt niet in deze browser.';document.querySelector('.masthead').after(note);}
const completeProfileIcon=profileIcon;
profileIcon=function(type,label=''){
 let points;
 if(['IPE','HEA','HEB'].includes(type)){const w=type==='IPE'?22:31,h=34,t=type==='HEB'?6:4,x=10,y=29,c=x+w/2;points=[[x,y],[x+w,y],[x+w,y+t],[c+t/2,y+t],[c+t/2,y+h-t],[x+w,y+h-t],[x+w,y+h],[x,y+h],[x,y+h-t],[c-t/2,y+h-t],[c-t/2,y+t],[x,y+t]];}
 if(type==='unequalAngle')points=[[10,26],[15,26],[15,58],[43,58],[43,63],[10,63]];
 if(type==='strip')points=[[10,43],[36,43],[36,51],[10,51]];
 if(!points)return completeProfileIcon(type,label);
 const path=pts=>'M'+pts.map(p=>p.join(' ')).join('L')+'Z',shift=([x,y])=>[x+36,y-17];const sides=points.map((p,i)=>{const n=points[(i+1)%points.length];return '<path d="'+path([p,n,shift(n),shift(p)])+'"/>';}).filter((_,i)=>type==='strip'?[0,1].includes(i):[0,1,5].includes(i)).join('');
 return '<svg class="profile-icon" viewBox="0 0 88 80" role="img" aria-label="'+esc(PROFILES[type]?.name||type)+'"><g fill="currentColor" fill-opacity=".08" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round">'+sides+'<path d="'+path(points)+'"/></g></svg>';
};
// Normalize catalog metadata without changing any tabulated engineering values.
PROFILES.UNP.catalog='UNP';
const sourcedArticle=applyCatalogArticle;
applyCatalogArticle=function(line,article){const next=sourcedArticle(line,article);if(Number.isFinite(article.supplierWeightKgPerM)&&article.supplierWeightKgPerM>0){next.weightSource=article.supplierId||article.price.sourceUrl;next.sourceDate=next.sourceDate||new Date().toISOString().slice(0,10);}return next;};
