/* Job workspace; calculation arithmetic remains in the existing tested core. */
const CUSTOMER_KEY='werkbank.v2.customers',DRAFT_KEY='werkbank.v2.draft';
let editingWork=null;
let jobTab='site',draftTimer=null,customerEditing=null;
const cloneJob=x=>JSON.parse(JSON.stringify(x));
function ensureJob(){if(!costState.job||typeof costState.job!=='object')costState.job={};const j=costState.job;for(const key of ['measurements','photos','work'])if(!Array.isArray(j[key]))j[key]=[];if(j.legacyOther===undefined)j.legacyOther=costState.other||0;return j;}
function customers(){const r=storageAdapter.read(CUSTOMER_KEY,[]);return r.ok&&Array.isArray(r.value)?r.value:[];}
function messageJob(text){const el=$('job-save-status');if(el)el.textContent=text;}
function persistDraft(){clearTimeout(draftTimer);if(!costState)return;readCostInput();const ok=safeSet(DRAFT_KEY,{id:savedProjectId,data:serializableState()});messageJob(ok?'Concept op dit apparaat bewaard · nog geen cloudsynchronisatie':'Opslaan mislukt. Exporteer de klus als back-up.');}
function queueDraft(){clearTimeout(draftTimer);draftTimer=setTimeout(persistDraft,450);}
function jobInput(id,label,value='',type='text'){return '<div><label for="'+id+'">'+label+'</label><input id="'+id+'" type="'+type+'" value="'+esc(value)+'"></div>';}
function jobRows(){const j=ensureJob();$('measurement-list').innerHTML=j.measurements.map((m,i)=>'<div class="job-row"><span>'+esc(m.name)+'<small>'+esc(m.value)+' '+esc(m.unit)+'</small></span><button class="ghost" data-measure-remove="'+i+'" aria-label="Verwijder maat '+esc(m.name)+'">Verwijder</button></div>').join('')||'<p class="muted">Nog geen maten vastgelegd.</p>';document.querySelectorAll('[data-measure-remove]').forEach(b=>b.onclick=()=>{j.measurements.splice(+b.dataset.measureRemove,1);jobRows();queueDraft();});$('job-photos').innerHTML=j.photos.map((p,i)=>'<figure><img src="'+p.data+'" alt="'+esc(p.name)+'"><figcaption><button class="ghost" data-photo-remove="'+i+'">Verwijder foto '+(i+1)+'</button></figcaption></figure>').join('');document.querySelectorAll('[data-photo-remove]').forEach(b=>b.onclick=()=>{j.photos.splice(+b.dataset.photoRemove,1);jobRows();queueDraft();});}
function renderSite(){const j=ensureJob();$('panel-site').innerHTML='<div class="job-panel"><h2>Opname op locatie</h2><div class="job-grid">'+jobInput('j-title','Naam van de klus',costState.project)+jobInput('j-location','Werklocatie',j.location)+jobInput('j-qty','Aantal eindproducten',costState.qty)+'<div class="wide"><label for="j-customer">Klant uit je bestand</label><select id="j-customer"><option value="">Losse klantgegevens</option>'+customers().map(c=>'<option value="'+esc(c.id)+'"'+(j.customerId===c.id?' selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select></div>'+jobInput('j-name','Klant / bedrijf',costState.klant)+jobInput('j-contact','Contactpersoon',j.contact)+jobInput('j-email','E-mail',j.email,'email')+jobInput('j-phone','Telefoon',j.phone,'tel')+'<div class="wide"><label for="j-description">Wat ga je maken of herstellen?</label><textarea id="j-description">'+esc(costState.omschrijving||'')+'</textarea></div></div><button class="ghost" id="save-customer">Klant bewaren in bestand</button><p id="customer-feedback" role="status"></p></div><div class="job-panel"><h2>Maten & notities</h2><div id="measurement-list"></div><div class="job-grid">'+jobInput('measure-name','Omschrijving, bijvoorbeeld opening')+jobInput('measure-value','Gemeten waarde')+'<div><label for="measure-unit">Eenheid</label><select id="measure-unit"><option>mm</option><option>cm</option><option>m</option><option>°</option></select></div><button class="ghost" id="add-measure">Maat toevoegen</button></div><p id="measure-error" class="job-error" role="status"></p><label for="j-notes">Interne opname- en meetnotities</label><textarea id="j-notes">'+esc(j.notes||'')+'</textarea><a class="support-link" href="#tools">'+uiIcon('tools')+' Rekentools openen</a></div><div class="job-panel"><h2>Foto’s & schetsen</h2><p class="muted">Voeg foto’s van de situatie of een handgetekende schets toe. Maximaal 6 foto’s, verkleind voor opslag op dit apparaat.</p><label for="job-photo-input">Foto kiezen of maken</label><input id="job-photo-input" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple><p id="photo-feedback" class="photo-loading" role="status"></p><div id="job-photos" class="job-photo-grid"></div></div>';
$('j-qty').inputMode='numeric';$('j-qty').oninput=e=>{costState.qty=e.target.value;$('c-qty').value=e.target.value;renderMaterials();renderCostTotals();queueDraft();};const bind={title:['project'],name:['klant'],description:['omschrijving'],location:['job','location'],contact:['job','contact'],email:['job','email'],phone:['job','phone'],notes:['job','notes']};for(const [id,path]of Object.entries(bind))$('j-'+id).oninput=e=>{if(path.length===1){costState[path[0]]=e.target.value;const old=$('c-'+path[0]);if(old)old.value=e.target.value;}else j[path[1]]=e.target.value;$('cost-title').textContent=costState.project||'Nieuwe klus';queueDraft();};$('j-customer').onchange=e=>{const c=customers().find(c=>c.id===e.target.value);j.customerId=c?.id||'';if(c){costState.klant=c.name;$('c-klant').value=c.name;for(const k of ['contact','email','phone'])j[k]=c[k]||'';}renderSite();queueDraft();};$('save-customer').onclick=()=>saveCustomerFromJob();$('measure-value').inputMode='decimal';$('add-measure').onclick=()=>{const name=$('measure-name').value.trim(),v=strictNumber($('measure-value').value);if(!name||!Number.isFinite(v)||v<=0){$('measure-error').textContent='Vul een omschrijving en een maat groter dan nul in.';return;}j.measurements.push({name,value:v,unit:$('measure-unit').value});$('measure-name').value='';$('measure-value').value='';$('measure-error').textContent='';jobRows();queueDraft();};$('job-photo-input').onchange=addJobPhotos;jobRows();}
async function compressJobPhoto(file){if(file.size>20*1024*1024)throw Error('Deze foto is groter dan 20 MB. Kies een kleinere foto.');const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Dit fotoformaat kan hier niet worden gelezen. Gebruik JPEG, PNG of WebP.'));i.src=url;});const ratio=Math.min(1,1280/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*ratio));canvas.height=Math.max(1,Math.round(img.height*ratio));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.7);if(data.length>650000)throw Error('Foto blijft te groot voor lokale opslag. Kies een kleinere foto.');return {id:uid(),name:file.name,data};}finally{URL.revokeObjectURL(url);}}
async function addJobPhotos(e){const j=ensureJob(),files=Array.from(e.target.files);e.target.disabled=true;const button=$('cost-save');button.disabled=true;$('photo-feedback').textContent='Foto’s verwerken…';let errors=[];for(const file of files){if(j.photos.length>=6){errors.push('Maximaal 6 foto’s per klus.');break;}try{j.photos.push(await compressJobPhoto(file));}catch(err){errors.push(err.message);}}if(costState.job===j){jobRows();persistDraft();$('photo-feedback').textContent=errors.join(' ')||'Foto’s toegevoegd.';}e.target.value='';e.target.disabled=false;if(button.isConnected)button.disabled=false;}
function saveCustomerFromJob(){const j=ensureJob(),name=costState.klant?.trim();if(!name){$('customer-feedback').textContent='Vul eerst een klantnaam in.';return;}const raw=storageAdapter.read(CUSTOMER_KEY,[]);if(!raw.ok||!Array.isArray(raw.value)){$('customer-feedback').textContent='Klantenbestand kan niet veilig worden gelezen.';return;}const c={id:j.customerId||uid(),name,contact:j.contact||'',email:j.email||'',phone:j.phone||''};if(safeSet(CUSTOMER_KEY,[c,...raw.value.filter(x=>x.id!==c.id)])){j.customerId=c.id;renderSite();$('customer-feedback').textContent='Klant bewaard.';queueDraft();}else $('customer-feedback').textContent='Bewaren mislukt. Je gegevens blijven in de klus staan.';}
function workTotal(){return ensureJob().work.reduce((sum,w)=>sum+Math.round(w.quantity*w.rate*100),0)/100;}
function syncWork(){const j=ensureJob();costState.other=strictNumber(j.legacyOther||0)+workTotal();if($('c-other'))$('c-other').value=costState.other;renderCostTotals();}
function renderJobWork(){editingWork=null;const j=ensureJob();$('job-work').innerHTML='<h2>Werkzaamheden & montage</h2><p class="muted">Bedragen gelden voor de hele klus, exclusief btw.</p><div id="work-list">'+j.work.map((w,i)=>'<div class="job-row"><span>'+esc(w.name)+'<small>'+esc(w.category)+' · '+fmt(w.quantity,2)+' '+esc(w.unit)+' × '+euro(w.rate)+'</small><b>'+euro(Math.round(w.quantity*w.rate*100)/100)+'</b></span><span><button class="ghost" data-work-edit="'+i+'">Bewerk</button><button class="ghost" data-work-remove="'+i+'" aria-label="Verwijder '+esc(w.name)+'">Verwijder</button></span></div>').join('')+'</div><div class="job-grid"><div><label for="work-category">Soort werk</label><select id="work-category"><option>Fabricage</option><option>Montage</option><option>Reis & vervoer</option><option>Uitbesteding</option><option>Overig</option></select></div>'+jobInput('work-name','Omschrijving, bijvoorbeeld lassen')+jobInput('work-qty','Hoeveelheid','1')+'<div><label for="work-unit">Eenheid</label><select id="work-unit"><option>uur</option><option>km</option><option>stuk</option></select></div>'+jobInput('work-rate','Kostentarief (€)')+'<button class="act" id="work-add">Werk toevoegen</button></div><p id="work-error" role="status" class="job-error"></p><p><b>Toegevoegde werkzaamheden: '+euro(workTotal())+'</b></p>';for(const id of ['work-qty','work-rate'])$(id).inputMode='decimal';$('work-add').onclick=()=>{const name=$('work-name').value.trim(),quantity=strictNumber($('work-qty').value),rate=strictNumber($('work-rate').value);if(!name||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(rate)||rate<0){$('work-error').textContent='Vul een omschrijving, positieve hoeveelheid en geldig tarief in.';return;}const entry={id:editingWork===null?uid():j.work[editingWork].id,name,quantity,rate,unit:$('work-unit').value,category:$('work-category').value};if(editingWork===null)j.work.push(entry);else j.work[editingWork]=entry;editingWork=null;syncWork();renderJobWork();queueDraft();};document.querySelectorAll('[data-work-edit]').forEach(b=>b.onclick=()=>{editingWork=+b.dataset.workEdit;const w=j.work[editingWork];for(const [id,key] of [['name','name'],['qty','quantity'],['rate','rate'],['unit','unit'],['category','category']])$('work-'+id).value=w[key];$('work-add').textContent='Wijziging bewaren';});document.querySelectorAll('[data-work-remove]').forEach(b=>b.onclick=()=>{editingWork=null;j.work.splice(+b.dataset.workRemove,1);syncWork();renderJobWork();queueDraft();});}
function saleView(){const result=$('cost-result');const span=Array.from(result.querySelectorAll('.cost-breakdown span')).find(x=>x.textContent==='Verkoopprijs excl. btw');return {complete:!result.querySelector('.err,.incomplete'),ex:span?.nextElementSibling?.textContent||'—',inc:result.querySelector('.big')?.textContent||'—'};}
const jobSticky=updateStickyTotal;updateStickyTotal=function(){jobSticky();const v=saleView();if($('sticky-cost')){$('sticky-cost').textContent=v.complete?v.ex:'Prijs onvolledig';const label=$('sticky-cost').previousElementSibling;if(label)label.textContent='Verkoopprijs excl. btw';}if($('customer-view'))$('customer-view').disabled=!v.complete;};
function customerView(){readCostInput();renderCostTotals();const v=saleView();if(!v.complete)return;const j=ensureJob(),overlay=document.createElement('section');overlay.className='job-customer-view';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Prijsindicatie voor de klant');overlay.innerHTML='<p>PRIJSINDICATIE</p><h1>'+esc(costState.project||'Je klus')+'</h1><p>'+esc(costState.klant||'')+'</p><p>'+esc(j.location||'')+'</p><p class="customer-copy">'+esc(costState.omschrijving||'')+'</p><div class="customer-price">'+esc(v.ex)+'</div><p>Exclusief btw · '+esc(v.inc)+' inclusief btw</p><p>Indicatie op basis van de huidige opname. Dit is nog geen offerte of factuur.</p><div class="customer-actions"><button class="ghost" id="customer-close">Terug naar klus</button><button class="act" id="customer-print">Print / bewaar PDF</button></div>';document.body.append(overlay);const wrap=document.querySelector('.wrap');wrap.inert=true;document.body.classList.add('customer-print');const close=()=>{wrap.inert=false;document.body.classList.remove('customer-print');overlay.remove();$('customer-view').focus();};$('customer-close').onclick=close;$('customer-print').onclick=()=>window.print();overlay.onkeydown=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){e.preventDefault();(document.activeElement===$('customer-close')?$('customer-print'):$('customer-close')).focus();}};$('customer-close').focus();}
const jobBaseCost=renderCostPage;renderCostPage=function(values,message){jobBaseCost(values,message);$('cost-content').querySelector(':scope > .readout[role="status"]')?.remove();ensureJob();$('cost-title').textContent=costState.project||'Nieuwe klus';document.querySelector('.project-fields').hidden=true;const tabs=document.querySelector('.cost-tabs');tabs.classList.add('job-tabs');const site=document.createElement('div');site.id='panel-site';site.setAttribute('role','tabpanel');site.setAttribute('aria-labelledby','tab-site');tabs.after(site);const tab=document.createElement('button');tab.id='tab-site';tab.dataset.tab='site';tab.setAttribute('role','tab');tab.setAttribute('aria-controls','panel-site');tab.textContent='Opname';tabs.prepend(tab);$('tab-labor').textContent='Werk';$('tab-overview').textContent='Prijs';Array.from(tabs.children).forEach((b,i)=>{b.onclick=()=>{jobTab=b.dataset.tab;designTab=jobTab==='site'?'materials':jobTab;Array.from(tabs.children).forEach(t=>{t.setAttribute('aria-selected',String(t===b));t.tabIndex=t===b?0:-1;});document.querySelectorAll('#cost-content>[role="tabpanel"]').forEach(p=>p.hidden=p.id!=='panel-'+jobTab);};b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const all=Array.from(tabs.children),n=e.key==='Home'?0:e.key==='End'?all.length-1:(i+(e.key==='ArrowRight'?1:all.length-1))%all.length;all[n].click();all[n].focus();}};});const legacy=document.createElement('details');legacy.className='job-panel';legacy.innerHTML='<summary>Overige kosten & bestaande arbeidsbegroting</summary>';const labor=$('panel-labor');while(labor.firstChild)legacy.append(labor.firstChild);labor.append(legacy);const work=document.createElement('div');work.id='job-work';work.className='job-panel';labor.prepend(work);$('c-other').readOnly=true;$('c-other').parentElement.title='Bestaande overige kosten plus werkzaamheden';const customer=document.createElement('button');customer.id='customer-view';customer.className='act';customer.textContent='Toon prijs aan klant';customer.onclick=customerView;$('panel-overview').prepend(customer);const status=document.createElement('p');status.id='job-save-status';status.className='job-status';status.setAttribute('role','status');status.textContent=message||'Preview · alleen opslag op dit apparaat';tabs.before(status);$('cost-save').textContent='Klus bewaren';$('cost-save').setAttribute('aria-label','Klus bewaren');$('cost-content').addEventListener('input',queueDraft);renderSite();renderJobWork();syncWork();$('tab-'+jobTab).click();};
const jobStart=startProject;startProject=function(){jobTab='site';jobStart();};const jobOpen=openSavedProject;openSavedProject=function(row){jobTab='site';jobOpen(row);};$('design-new').onclick=startProject;$('library-new').onclick=startProject;
const jobSave=saveCalculation;saveCalculation=function(){jobSave();const text=$('job-save-status')?.textContent||'';if(text==='Calculatie bewaard.'){persistDraft();messageJob('Klus bewaard op dit apparaat.');}};
const jobDashboard=renderDashboard;renderDashboard=function(){jobDashboard();document.querySelector('.dashboard-title').textContent='Klussen';$('design-new').textContent='+ Nieuwe klus';const empty=document.querySelector('.recent-empty');if(empty&&!savedProjects().length)empty.innerHTML='<b>Van opname naar een duidelijke prijs.</b><p>Kies een klant, leg maten vast en verzamel materiaal en werk in één klus.</p>';let resume=$('job-resume');if(resume)resume.remove();const raw=storageAdapter.read(DRAFT_KEY,null);if(raw.ok&&raw.value?.data){resume=document.createElement('button');resume.id='job-resume';resume.className='recent-row';resume.textContent='Verder met concept: '+(raw.value.data.project||'Naamloze klus');resume.onclick=()=>{if(!allowDiscard())return;savedProjectId=raw.value.id||null;jobTab='site';history.pushState(null,'','#kostprijs');hidePages();$('cost').hidden=false;renderCostPage(migrateCalculation(raw.value.data));setNav('home');cleanProject=serial();};$('recent-design').before(resume);}};
// Een klus definitief verwijderen uit de lijst (kleine bug: dit kon nog helemaal niet). Losse,
// benoemde functie i.p.v. inline in de knop, zodat een latere laag (bv. crm/) 'm kan wrappen om
// zijn eigen gekoppelde data (acties, contactlog) ook op te ruimen, zonder dat deze laag daar
// iets van hoeft te weten. confirmFn is optioneel (standaard de echte confirm()) zodat dit ook
// zonder browser-dialoog te testen is.
function deleteProject(id,confirmFn){confirmFn=confirmFn||(typeof confirm!=='undefined'?confirm:()=>true);const list=safeGet(STORE.calculations,[]);const row=list.find(x=>x.id===id);if(!row)return false;if(!confirmFn('Klus "'+(row.data.project||'Naamloze klus')+'" verwijderen? Dit kan niet ongedaan worden gemaakt.'))return false;safeSet(STORE.calculations,list.filter(x=>x.id!==id));return true;}
const jobBaseProjectLibrary=renderProjectLibrary;renderProjectLibrary=function(){jobBaseProjectLibrary();const list=safeGet(STORE.calculations,[]);$('all-projects').querySelectorAll('.recent-row[data-project]').forEach(btn=>{if(btn.parentElement.classList.contains('job-project-row'))return;const wrap=document.createElement('div');wrap.className='job-project-row';btn.parentNode.insertBefore(wrap,btn);wrap.appendChild(btn);const del=document.createElement('button');del.type='button';del.className='ghost';del.textContent='Verwijderen';del.setAttribute('aria-label','Klus verwijderen: '+(list.find(x=>x.id===btn.dataset.project)?.data.project||'Naamloze klus'));del.onclick=()=>{if(deleteProject(btn.dataset.project))renderProjectLibrary();};wrap.appendChild(del);});};

const customerPage=document.createElement('section');customerPage.id='customer-page';customerPage.hidden=true;document.querySelector('.wrap').append(customerPage);
function renderCustomers(){customerPage.innerHTML='<h1>Klanten</h1><p class="job-intro">Kies een klant bij je volgende klus. Gegevens blijven in deze preview op dit apparaat.</p>'+customers().map(c=>'<div class="job-panel"><b>'+esc(c.name)+'</b><p>'+esc(c.contact||'')+'<br>'+esc(c.email||'')+'<br>'+esc(c.phone||'')+'</p><button class="ghost" data-customer-edit="'+esc(c.id)+'">Bewerken</button></div>').join('')+'<div class="job-panel"><h2 id="customer-form-title">Klant toevoegen</h2><div class="job-grid">'+jobInput('client-name','Naam / bedrijf')+jobInput('client-contact','Contactpersoon')+jobInput('client-email','E-mail','','email')+jobInput('client-phone','Telefoon','','tel')+'</div><button class="act" id="client-save">Klant bewaren</button><button class="ghost" id="client-cancel">Annuleren</button><p id="client-status" role="status"></p></div>';customerEditing=null;document.querySelectorAll('[data-customer-edit]').forEach(b=>b.onclick=()=>{const c=customers().find(x=>x.id===b.dataset.customerEdit);customerEditing=c.id;for(const k of ['name','contact','email','phone'])$('client-'+k).value=c[k]||'';$('customer-form-title').textContent='Klant bewerken';$('client-name').focus();});$('client-cancel').onclick=renderCustomers;$('client-save').onclick=()=>{const c={id:customerEditing||uid()};for(const k of ['name','contact','email','phone'])c[k]=$('client-'+k).value.trim();if(!c.name){$('client-status').textContent='Vul een klantnaam in.';return;}const raw=storageAdapter.read(CUSTOMER_KEY,[]);if(!raw.ok||!Array.isArray(raw.value)||!safeSet(CUSTOMER_KEY,[c,...raw.value.filter(x=>x.id!==c.id)])){$('client-status').textContent='Bewaren mislukt; bestaande gegevens zijn niet overschreven.';return;}renderCustomers();$('client-status').textContent='Klant bewaard.';};}
const jobHide=hidePages;hidePages=function(){if(costState&&!$('cost').hidden)persistDraft();jobHide();customerPage.hidden=true;};
const jobRoute=routeHash;routeHash=function(){if(location.hash==='#klanten'){hidePages();customerPage.hidden=false;renderCustomers();setNav('klanten');return;}jobRoute();if(location.hash==='#tools'&&costState){let back=$('job-return');if(!back){back=document.createElement('a');back.id='job-return';back.href='#kostprijs';back.className='job-tool-return';back.textContent='← Terug naar je klus';$('tool-directory').prepend(back);}}};window.removeEventListener('hashchange',jobRoute);window.removeEventListener('popstate',jobRoute);window.addEventListener('hashchange',routeHash);window.addEventListener('popstate',routeHash);
const navCustomer=document.querySelector('.nav-btn[data-route="prijzen"]');navCustomer.dataset.route='klanten';navCustomer.onclick=()=>{location.hash='klanten';};navCustomer.innerHTML=uiIcon('document')+'Klanten';navCustomer.setAttribute('aria-label','Klanten');document.querySelector('.nav-btn[data-route="home"]').innerHTML=uiIcon('document')+'Klussen';document.querySelector('.nav-btn[data-route="tools"]').innerHTML=uiIcon('tools')+'Gereedschap';document.querySelector('#design-settings .card:last-child').innerHTML='<h2>Klussenpreview 01</h2><p>Klussen, klanten en foto’s worden alleen op dit apparaat bewaard. Accounts, cloudsynchronisatie, offertes en factuurverzending volgen in latere fasen.</p><a href="#prijzen">Materiaalprijzen beheren</a>';
// Photo URLs are restricted on import; never inject arbitrary imported src attributes.
const jobValidate=validateCalculationPayload;validateCalculationPayload=function(obj){const r=jobValidate(obj);if(!r.ok)return r;const j=r.data.job;if(j){if(typeof j!=='object'||!Array.isArray(j.photos)||j.photos.length>6||j.photos.some(p=>typeof p.data!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(p.data)||p.data.length>650000)||!Array.isArray(j.work)||j.work.some(w=>!Number.isFinite(w.quantity)||w.quantity<=0||!Number.isFinite(w.rate)||w.rate<0)||!Array.isArray(j.measurements))return {ok:false,error:'Ongeldige klusgegevens'};}return r;};
const resumeAtBoot=storageAdapter.read(DRAFT_KEY,null);
routeHash();
if(location.hash==='#kostprijs'&&resumeAtBoot.ok&&resumeAtBoot.value?.data){savedProjectId=resumeAtBoot.value.id||null;renderCostPage(migrateCalculation(resumeAtBoot.value.data));setNav('home');}
cleanProject=serial();
